### ISSUE TITLE
Judul

### ISSUE THREAD

**Issue by fiqgant** [ezza022/covid-19-news#1]
Keren aja, terus perdalami ilmu walupun disana ga ada yg ngajarin

**Comment by ezza022** [comment]
> Keren aja, terus perdalami ilmu walupun disana ga ada yg ngajarin

iya pak, itu cuma ngincar sertifikat untuk prakerja, jadinya ganiat gitu buatnya hehe

**Comment by fiqgant** [comment]
Aku abg leting mu :) tanya aja senior mu kenal ga ama taufiqurrahman

**Comment by ezza022** [comment]
angkatan berapa bg

**Comment by fiqgant** [comment]
2014 sob
